---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: "    https://api.netlify.com/build_hooks/5c6cf353d486da5fceede517"
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: document
  path: data/paramsite.json
  label: Configuration
upload_dir: ''
public_path: https://res.cloudinary.com/clairejuillard/w_900
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.54.0
